export default interface Employee {
  id: number
  company_id: number
  num: string
  display_name: string
  base_pension_num: string
  employment_insurance_reference_number: string
  birth_date: string
  entry_date: string
  retire_date: string
  user_id: number
  profile_rule: {
    id: number
    company_id: number
    employee_id: number
    last_name: string
    first_name: string
    last_name_kana: string
    first_name_kana: string
    zipcode1: number
    zipcode2: number
    prefecture_code: number
    address: string
    address_kana: string
    phone1: number
    phone2: number
    phone3: number
    residential_zipcode1: number
    residential_zipcode2: number
    residential_prefecture_code: number
    residential_address: string
    residential_address_kana: string
    employment_type: string
    title: string
    gender: string
    married: true
    is_working_student: true
    widow_type: string
    disability_type: string
    email: string
    householder_name: string
    householder: string
  }
  health_insurance_rule: {
    id: number
    company_id: number
    employee_id: number
    entried: true
    health_insurance_salary_calc_type: string
    health_insurance_bonus_calc_type: string
    manual_health_insurance_amount_of_employee_salary: number
    manual_health_insurance_amount_of_employee_bonus: number
    manual_health_insurance_amount_of_company_salary: number
    manual_health_insurance_amount_of_company_bonus: number
    care_insurance_salary_calc_type: string
    care_insurance_bonus_calc_type: string
    manual_care_insurance_amount_of_employee_salary: number
    manual_care_insurance_amount_of_employee_bonus: number
    manual_care_insurance_amount_of_company_salary: number
    manual_care_insurance_amount_of_company_bonus: number
    reference_num: string
    standard_monthly_remuneration: number
  }
  welfare_pension_insurance_rule: {
    id: number
    child_allowance_contribution_bonus_calc_type: string
    child_allowance_contribution_salary_calc_type: string
    company_id: number
    employee_id: number
    entried: true
    manual_child_allowance_contribution_amount_bonus: number
    manual_child_allowance_contribution_amount_salary: number
    manual_welfare_pension_insurance_amount_of_company_bonus: number
    manual_welfare_pension_insurance_amount_of_company_salary: number
    manual_welfare_pension_insurance_amount_of_employee_bonus: number
    manual_welfare_pension_insurance_amount_of_employee_salary: number
    reference_num: string
    standard_monthly_remuneration: number
    welfare_pension_insurance_bonus_calc_type: string
    welfare_pension_insurance_salary_calc_type: string
  }
  dependent_rules: {
    id: number
    company_id: number
    employee_id: number
    last_name: string
    first_name: string
    last_name_kana: string
    first_name_kana: string
    gender: string
    relationship: string
    birth_date: string
    residence_type: string
    zipcode1: string
    zipcode2: string
    prefecture_code: number
    address: string
    address_kana: string
    base_pension_num: string
    income: number
    annual_revenue: number
    disability_type: string
    occupation: string
    annual_remittance_amount: number
    employment_insurance_receive_status: string
    employment_insurance_receives_from: string
    phone_type: string
    phone1: number
    phone2: number
    phone3: number
    social_insurance_and_tax_dependent: string
    social_insurance_dependent_acquisition_date: string
    social_insurance_dependent_acquisition_reason: string
    social_insurance_other_dependent_acquisition_reason: string
    social_insurance_dependent_disqualification_date: string
    social_insurance_dependent_disqualification_reason: string
    social_insurance_other_dependent_disqualification_reason: string
    tax_dependent_acquisition_date: string
    tax_dependent_acquisition_reason: string
    tax_other_dependent_acquisition_reason: string
    tax_dependent_disqualification_date: string
    tax_dependent_disqualification_reason: string
    tax_other_dependent_disqualification_reason: string
    non_resident_dependents_reason: string
  }[]
  bank_account_rule: {
    id: number
    company_id: number
    employee_id: number
    bank_name: string
    bank_name_kana: string
    bank_code: string
    branch_name: string
    branch_name_kana: string
    branch_code: string
    account_number: string
    account_name: string
    account_type: string
  }
  basic_pay_rule: {
    id: number
    company_id: number
    employee_id: number
    pay_calc_type: string
    pay_amount: number
  }
  payroll_calculation: true
  company_reference_date_rule_name: string
}
